### ISSUE TITLE
wrong crosswords processing by indexer

### ISSUE THREAD

**Issue by sburn** [Maxime2/dataparksearch#10] opened 2016-05-29 19:28 UTC
Indexer is putting alt, title attributes content of IMG, A and LINK tags to crosswords section of the same document, instead of putting them as crosswords of documents linked by that tags.

Commented out code in parsehtml.c:

```
 else if (href && CrosSec && alt != NULL && TAG_WITH_CROSSATTRIBUTE ) {
    Item.href = href;
    Item.section = CrosSec->section;
    Item.section_name = CrosSec->name;
    Item.strict = CrosSec->strict;
    Item.str = alt;
    Item.len = dps_strlen(alt);
    putItem(Indexer, Doc, &Item);
}
 else if (href && CrosSec && title != NULL && TAG_WITH_CROSSATTRIBUTE ) {
    Item.href = href;
    Item.section = CrosSec->section;
    Item.section_name = CrosSec->name;
    Item.strict = CrosSec->strict;
    Item.str = title;
    Item.len = dps_strlen(title);
    putItem(Indexer, Doc, &Item);
}
```

**Comment by Maxime2** [comment] 2016-06-07 08:32
That is intended behaviour. Crossword section belongs to both documents, however crosswords section value stored with a document consists only of word found under links or alt and tittle attributes with links on that document, not of all those on pages which link to that document.

Though the index population was correct, the value of crossword section was not. It is now fixed and changes were pushed into repository.

Thank you!

**Closed by Maxime2** 2016-06-07 08:32 UTC
